server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/campwithmedb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: campwithme
    password: campwithme
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 0a557f7be997372534d371890da6767a
            client-secret: atQW4yv8wljWZ07iBgYyV07fbOlzCFLb
            redirect_uri: http://localhost:8080/api/auth/kakao/login
            authorization-grant-type: authorization_code
            scope: [ profile, account_email ]
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: 7ZmA656AIOuTneygkOyZlSDquLDsm5AgMeydvOywqALdlsKJL3234jklsdjfaKJDLnflkasdf

logging:
  level:
    '[company.gonggam]': DEBUG
    '[org.hibernate.type]': TRACE

python:
  server:
    url: http://172.16.17.243:8000